services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: passman
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: api
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env.docker
    depends_on:
      - mysql

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: web
    ports:
      - "3001:80"

volumes:
  mysql-data:
