services:
  traefik:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=chaudharynizam10@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      update_config:
        order: stop-first
        delay: 5s
        failure_action: rollback
        monitor: 20s
        max_failure_ratio: 0.2

  passman-fe:
    image: ghcr.io/nizam-chaudhary/passman-fe:${GIT_COMMIT_HASH:-latest}
    labels:
      - traefik.enable=true
      - traefik.http.services.passman.loadbalancer.server.port=80
      - traefik.http.routers.passman.rule=Host(`passman.live`)
      - traefik.http.routers.passman.entrypoints=websecure
      - traefik.http.routers.passman.tls.certresolver=myresolver
    deploy:
      update_config:
        order: start-first
        delay: 5s
        # parallelism: 2
        failure_action: rollback
        monitor: 20s
        max_failure_ratio: 0.2

  passman-be:
    image: ghcr.io/nizam-chaudhary/passman-be:${GIT_COMMIT_HASH:-latest}
    labels:
      - traefik.enable=true
      - traefik.http.services.passman-be.loadbalancer.server.port=3000
      - traefik.http.routers.passman-be.rule=Host(`api.passman.live`)
      - traefik.http.routers.passman-be.entrypoints=websecure
      - traefik.http.routers.passman-be.tls.certresolver=myresolver
    env_file:
      - ./apps/api/.env.docker
    deploy:
      update_config:
        order: start-first
        delay: 5s
        # parallelism: 2
        failure_action: rollback
        monitor: 20s
        max_failure_ratio: 0.2

volumes:
  letsencrypt:
