packages:
  - packages/*
  - apps/*

syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true

ignoredBuiltDependencies:
  - nx
  - '@swc/core'
  - esbuild
  - protobufjs
  - core-js

  
