name: Build and Deploy Passman to Docker Swarm

on:
  workflow_dispatch:

jobs:
  build-and-publish-web-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add environment variables
        run: |
          echo ${{ secrets.FE_APP_ENV_FILE }} >> .env.production

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Web Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/web/Dockerfile
          target: web
          push: true
          tags: |
            ghcr.io/nizam-chaudhary/passman-fe:latest
            ghcr.io/nizam-chaudhary/passman-fe:${{ github.sha }}

  build-and-publish-api-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/api/Dockerfile
          target: api
          push: true
          tags: |
            ghcr.io/nizam-chaudhary/passman-be:latest
            ghcr.io/nizam-chaudhary/passman-be:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-publish-web-docker-image
      - build-and-publish-api-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Create Git commit hash
        run: |
          export GIT_COMMIT_HASH=${{ github.sha }}

      - name: Create Docker context and set in use
        run: |
          ssh-keyscan -H passman.live >> ~/.ssh/known_hosts
          docker context create passman --docker "host=ssh://ubuntu@passman.live"
          docker context use passman
          echo ${{ secrets.BE_APP_ENV_FILE }} >> ./apps/api/.env.docker

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker stack deploy
        run: |
          docker stack config -c docker-stack.yml | docker stack deploy -c - passman -d --with-registry-auth
